# Generated by Django 5.2.8 on 2026-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('exp_category', models.CharField(max_length=200)),
                ('exp_amount', models.BigIntegerField()),
            ],
        ),
    ]
